# Generated by Django 4.2.3 on 2023-08-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcontent',
            options={'verbose_name_plural': 'Post content'},
        ),
    ]
