# Generated by Django 4.2.3 on 2023-07-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='postcontent',
            unique_together={('level', 'post')},
        ),
    ]
