# Generated by Django 4.2.3 on 2023-07-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postcontent_level_alter_postcontent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcontent',
            unique_together={('post',)},
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='level',
        ),
    ]
