# Generated by Django 4.2.3 on 2023-08-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postcontent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='postcontent',
            unique_together={('post', 'level')},
        ),
    ]
