# Generated by Django 4.2.3 on 2023-08-08 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postcontent_level_alter_postcontent_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContentPinyin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin_content', models.TextField()),
                ('post_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinyin', to='posts.postcontent')),
            ],
            options={
                'verbose_name_plural': 'Post content pinyin',
                'db_table': 'posts_post_content_pinyin',
            },
        ),
    ]
