# Generated by Django 4.2.3 on 2023-08-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcontentpinyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontent',
            name='content',
            field=models.JSONField(),
        ),
    ]
