# Generated by Django 4.2.3 on 2023-08-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('level', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='post.post')),
            ],
            options={
                'verbose_name_plural': 'Post content',
                'db_table': 'post_post_content',
            },
        ),
        migrations.CreateModel(
            name='PostContentPinyin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinyin_content', models.TextField()),
                ('post_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinyin', to='post.postcontent')),
            ],
            options={
                'verbose_name_plural': 'Post content pinyin',
                'db_table': 'post_post_content_pinyin',
            },
        ),
        migrations.CreateModel(
            name='PostContentAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.CharField(max_length=255)),
                ('timestamps', models.JSONField()),
                ('post_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='post.postcontent')),
            ],
            options={
                'verbose_name_plural': 'Post content audio',
                'db_table': 'post_post_content_audio',
            },
        ),
    ]
