# Generated by Django 4.2.3 on 2023-08-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postcontent_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontentaudio',
            name='timestamps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
