# Generated by Django 4.2.3 on 2023-08-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postcontentaudio_timestamps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostContentAudio',
            new_name='ContentAudio',
        ),
        migrations.RenameModel(
            old_name='PostContentPinyin',
            new_name='ContentPinyin',
        ),
        migrations.AlterModelOptions(
            name='contentaudio',
            options={'verbose_name_plural': 'Content audio'},
        ),
        migrations.AlterModelTable(
            name='contentaudio',
            table='post_content_audio',
        ),
        migrations.AlterModelTable(
            name='contentpinyin',
            table='post_content_pinyin',
        ),
    ]
