# Generated by Django 4.2.3 on 2023-08-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(db_index=True, max_length=255, verbose_name='Traditional Characters')),
                ('simplified', models.CharField(db_index=True, max_length=255, verbose_name='Simplified Characters')),
                ('pinyin', models.CharField(db_index=True, max_length=255, verbose_name='Pinyin Letters')),
                ('english', models.TextField()),
            ],
            options={
                'db_table': 'cedict_words',
            },
        ),
    ]
